fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
  forge_modules:
    supervisor: "proletaryo-supervisor"
    nodejs: "puppet-nodejs"
  symlinks:
    ghost: "#{source_dir}"
